name: ZombieVsPlayer
version: 2.0.0
description: Zombie versus Player Minigame
website: http://dev.bukkit.org/bukkit-plugins/zombievsplayer/
author: Aubli
main: me.Aubli.ZvP.ZvP

commands:     
     zvp:
          description: Basic Commands.
          usage: |
                 /<command>
                 /<command> setlang [language]
                 /<command> setspawn
                 /<command> setspecspawn
                 /<command> addkit [name]
     test:
          description: test command
          usage: /<command>