name: ZombieVsPlayer
version: 2.6.2
description: Zombie versus Player Minigame
website: http://dev.bukkit.org/bukkit-plugins/zombievsplayer/
author: Aubli
load: POSTWORLD
softdepend: [Multiverse-Core]
main: me.Aubli.ZvP.ZvP

commands:     
     zvp:
          description: ZombieVsPlayer Commands
          usage: |
                 /<command> help
     zvptest:
          description: ZvP Test command [Requires DebugMode]
          usage: /<command>