name: ZombieVsPlayer
version: 2.8.7
description: Fight against zombies with a lot of extra features!
website: http://dev.bukkit.org/bukkit-plugins/zombievsplayer/
author: Aubli
load: POSTWORLD
softdepend: [Multiverse-Core, Vault, WorldGuard, WorldEdit]
main: me.Aubli.ZvP.ZvP

commands:     
     zvp:
          description: ZombieVsPlayer Commands
          usage: |
                 /<command> help
     zvptest:
          description: ZvP Test command [Requires DebugMode]
          usage: /<command>