name: ZombieVsPlayer
version: 2.0.6
description: Zombie versus Player Minigame
website: http://dev.bukkit.org/bukkit-plugins/zombievsplayer/
author: Aubli
load: POSTWORLD
softdepend: [Multiverse-Core]
main: me.Aubli.ZvP.ZvP

commands:     
     zvp:
          description: Basic Commands.
          usage: |
                 /<command>
                 /<command> help
                 /<command> reload
                 /<command> save
                 /<command> status
                 /<command> list
                 /<command> leave
                 /<command> stop
                 /<command> stop [Arena]
                 /<command> addkit [name]
                 /<command> removekit [name]
                 /<command> pos1/pos2
                 /<command> add arena
                 /<command> add lobby
                 /<command> remove arena [Arena]
                 /<command> remove lobby [lobby]
     zvptest:
          description: test command
          usage: /<command>