name: ZombieVsPlayer
version: 1.2.1
description: Zombie versus Player Minigame
website: http://dev.bukkit.org/bukkit-plugins/zombievsplayer/
author: Aubli
main: me.Aubli.ZvP.ZvP

commands:
     zvp:
          description: Basic Commands.
          usage: |
                 /<command>
                 /<command> setlang [language]
                 /<command> setspawn
                 /<command> setspecspawn
                 /<command> addkit [name]                 
     zvpstart:
          description: Start a Zombie vs. Player Game!
          usage: /<command> [Rounds]
     zvpstop:
          description: Stops a Zombie vs. Player Game!
          usage: /<command>
     zvpsell:
          description: Sell the item that you hold!
          usage: /<command>
     zvpjoin:
          description: Let you join a running game!
          usage: /<command>
     zvpleave:
          description: Let you leave a running game!
          usage: /<command>